# Generated by Django 5.2.3 on 2025-06-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bricks_app', '0005_rename_bill_status_paymentmaster_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillDetails',
        ),
        migrations.DeleteModel(
            name='PaymentMaster',
        ),
        migrations.DeleteModel(
            name='VehicleMaster',
        ),
        migrations.RemoveField(
            model_name='customermaster',
            name='Bill_Amount',
        ),
        migrations.RemoveField(
            model_name='customermaster',
            name='Paid_Amount',
        ),
        migrations.RemoveField(
            model_name='customermaster',
            name='Pending_Amount',
        ),
    ]
