# Generated by Django 5.2.3 on 2025-06-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks_app', '0006_delete_billdetails_delete_paymentmaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.CharField(max_length=20)),
                ('Customer_Name', models.CharField(max_length=255)),
                ('Customer_Phone', models.BigIntegerField()),
                ('Customer_Address', models.CharField(max_length=200)),
                ('Gps_Imei_No', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=200)),
                ('Sim_No', models.CharField(max_length=200)),
                ('Vehicle_No', models.CharField(max_length=200)),
                ('Vehicle_Name', models.CharField(max_length=200)),
                ('Insurance_Name', models.CharField(max_length=200)),
                ('Insurance_End_Date', models.DateField(null=True)),
                ('Next_Renewal_Date', models.DateField(null=True)),
            ],
        ),
    ]
