# Generated by Django 5.2.3 on 2025-06-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks_app', '0007_devicemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tea', 'Tea'), ('coffee', 'Coffee'), ('juice', 'Juice'), ('sweets', 'Sweets'), ('tiffins', 'Tiffins'), ('counter', 'Counter Products')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
